# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    email:
        digits: 6
        enabled: true
        sender_email: no-reply@test.com
        sender_name: John Doe
    trusted_device:
        enabled: true
        lifetime: 5184000 # 30 days
        extend_lifetime: false
        cookie-name: trusted_device
        cookie-secure: false
        cookie-same-site: lax
        cookie-path: /